### ISSUE TITLE
ADC C++ example does not compile

### ISSUE THREAD

**Issue by chutsu** [emlid/Navio2#11]
In `Navio2/C++/Examples/ADC` the code does not compile I get the following error:

![screenshot - 16-05-09 - 10 32 36 am](https://cloud.githubusercontent.com/assets/91460/15116446/632c4f70-15d1-11e6-81ec-5728a2b94b25.png)

Maybe use a pointer and `malloc` it on the fly?

**Comment by chutsu** [comment]
changing the `results` variable seemed to have worked.

![screenshot - 16-05-09 - 10 44 34 am](https://cloud.githubusercontent.com/assets/91460/15116878/15617a0c-15d3-11e6-8f60-f13c907ed843.png)

**Comment by staroselskii** [comment]
Fixed a long time ago. Thanks!
