### ISSUE TITLE
HOW to compile C++ drivers

### ISSUE THREAD

**Issue by tizianoC** [emlid/Navio2#12]
I have tried to compile Ublox.cpp in the C++/Navio folder, running 

gcc Ublox.cpp

but it doesn't work.

May I use another compiler?
Or any other suggestions?

Thanks a lot.

**Comment by staroselskii** [comment]
If you want to compile an example, `cd` into an Examples/<example> and `make`
BTW, gcc is by a C compiler by default.

**Comment by tizianoC** [comment]
I compiled the example but in any case I get

> Error: can not open SPI device.

The problem seems to be that I have to compile the drivers that, I think, are in the folder C ++ / Navio. I'm right?

**Comment by staroselskii** [comment]
Please, follow our [docs](https://docs.emlid.com/navio2/Navio-dev/navio-repository-cloning/). Are you using our [image](https://docs.emlid.com/navio2/Navio-APM/configuring-raspberry-pi/)?
