### ISSUE TITLE
Python driver for LSM9DS1 

### ISSUE THREAD

**Issue by gmsanchez** [emlid/Navio2#13]
Could this implementation work with Navio2?

https://github.com/hoihu/projects/blob/master/raspi-hat/lsm9ds1.py

Cheers!

**Comment by staroselskii** [comment]
Hello there!

Unfortunately, no. As this implementation is hardly bound to I2C.

**Comment by gmsanchez** [comment]
I've written a Python driver for lsm9ds1 and created a pull request. Hope it helps!

**Comment by staroselskii** [comment]
Oh, nice job! We'll try to test it as soon as possible and get back at your. Thank you!
