### ISSUE TITLE
build AHRS with CC.

### ISSUE THREAD

**Issue by karu2003** [emlid/Navio2#15]
It's a pity

Makefile for AHRS does not support the CC.

**Comment by staroselskii** [comment]
Could you elaborate on this one? And maybe make a PR?

**Comment by staroselskii** [comment]
I'm closing this one. We do support CXX (C++ compiler) variable. Take a look [here](https://github.com/emlid/Navio2/blob/master/C%2B%2B/Examples/ADC/Makefile#L1)!
