### ISSUE TITLE
pigpio.h no such file or directory:  on master branch

### ISSUE THREAD

**Issue by vkotaru** [emlid/Navio2#31]
Hi,

When tried compiling the C++ examples on master branch, I got the this error. 

```
In file included from Navio+/RCInput_Navio.cpp:1:0:
Navio+/RCInput_Navio.h:4:20: fatal error: pigpio.h: No such file or directory
compilation terminated.
```

I was able to compile C++ examples on navio2 branch, however, the LED example didnot change the color of the led on navio2.

**Comment by IgorAnohin** [comment]
Hello, @vkotaru!
Please, back to master branch and try to do this:
`sudo apt-get update`
`sudo apt-get install pigpio`

**Comment by vkotaru** [comment]
@IgorAnohin  Thanks.
