### ISSUE TITLE
Is Navio2 compatible with the new Raspberry Pi4?

### ISSUE THREAD

**Issue by JonathanPlasse** [emlid/Navio2#42]
Hi,
I would like to use the Raspberry Pi4 with Navio2.
Is it possible?

**Comment by urpylka** [comment]
@JonathanPlasse already 2 weeks
https://community.emlid.com/t/raspbian-buster-with-raspberry-pi-4-support-for-navio/17267

**Comment by staroselskii** [comment]
Thanks, @urpylka 

Closing this one.
