### ISSUE TITLE
Suggestion for Navio2 C++ library

### ISSUE THREAD

**Issue by chutsu** [emlid/Navio2#9]
I've been toying around with the C++ library, and wasn't satisfied with the way the code is layed out in the repo. As a programmer I was expecting a Makefile for the Navio C++ portion that builds the library and installs it to the right place so I can link it. I instead made my own, check it out [here](https://github.com/chutsu/navio2-cpp).

It essentially builds the library and examples. I would happily transfer this work to you guys if you like.

**Comment by staroselskii** [comment]
@chutsu 

It'd be very nice to see a PR! We can discuss it in details there, alright?

**Comment by chutsu** [comment]
Well the repo I made only contains your C++ library code, not the python and scripts. So I'm not sure a PR here makes sense. Plus I didn't fork from the github repo so PR is not possible I don't think.
